spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.map.mutual.side.common.config.JPANamingConfig
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    database: SQL_SERVER
  datasource:
    driverclassname: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://person.jjhserverworld.pe.kr:49153;instanceName=SpringApplication;DatabaseName=INITDB
    username: SA
    password: mutual#!12


  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  output:
    ansi:
      enabled: always

server:
  port: 3333
